# Generated by Django 2.2 on 2019-04-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('codbarbero', models.AutoField(primary_key=True, serialize=False)),
                ('barberonom', models.CharField(max_length=150)),
                ('fecharegistro', models.DateField()),
                ('descripcion', models.TextField()),
                ('correo', models.EmailField(max_length=250)),
            ],
            options={
                'verbose_name': 'Barbero',
                'verbose_name_plural': 'Barberos',
                'ordering': ['barberonom'],
            },
        ),
    ]
