# Generated by Django 2.2 on 2019-04-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaBarberia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codcliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('clientenom', models.CharField(max_length=150, verbose_name='Cliente')),
                ('fecharegistro', models.DateField()),
                ('correo', models.EmailField(max_length=250, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['clientenom'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codserv', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('servicio', models.CharField(max_length=150, verbose_name='Servicio')),
                ('nomcorto', models.CharField(max_length=50, verbose_name='Abreviatura')),
                ('fecharegistro', models.DateField()),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nomcorto'],
            },
        ),
    ]
