# Generated by Django 2.2 on 2019-04-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaBarberia', '0002_cliente_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=1, max_length=12, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
