# Generated by Django 2.2 on 2019-04-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaBarberia', '0003_cliente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codreserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('obs', models.TextField()),
                ('codbarbero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ReservaBarberia.Barbero')),
                ('codclie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ReservaBarberia.Cliente')),
                ('codserv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ReservaBarberia.Servicio')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha'],
            },
        ),
    ]
